[project]
name = "catalog-searcher"
version = "2.0.0-dev"
dependencies = [
    "cql-parser",
    "environs",
    "flask",
    "furl",
    "paste",
    "pymods",
    "requests",
    "uritemplate",
    "urlobject",
    "waitress",
]

[project.optional-dependencies]
test = [
    "httpretty",
    "psutil",
    "pytest",
    "pytest-cov",
    "pytest-datadir",
]

[project.scripts]
catalog-searcher = 'catalog_searcher.server:run'
